 docker rm $(sudo docker ps -a -q)
 docker rmi pacur/pacur-archlinux
 docker rmi pacur/pacur-amazonlinux-2016.09
 docker rmi pacur/pacur-amazonlinux-2017.03
 docker rmi pacur/pacur-amazonlinux-2017.09
 docker rmi pacur/pacur-amazonlinux-2017.12
 docker rmi pacur/pacur-amazonlinux-1
 docker rmi pacur/pacur-amazonlinux-2
 docker rmi pacur/pacur-centos-6
 docker rmi pacur/pacur-centos-7
 docker rmi pacur/pacur-debian-jessie
 docker rmi pacur/pacur-debian-stretch
 docker rmi pacur/pacur-debian-wheezy
 docker rmi pacur/pacur-debian-buster
 docker rmi pacur/pacur-fedora-21
 docker rmi pacur/pacur-fedora-22
 docker rmi pacur/pacur-fedora-23
 docker rmi pacur/pacur-fedora-24
 docker rmi pacur/pacur-fedora-25
 docker rmi pacur/pacur-fedora-26
 docker rmi pacur/pacur-fedora-27
 docker rmi pacur/pacur-fedora-28
 docker rmi pacur/pacur-fedora-29
 docker rmi pacur/pacur-fedora-30
 docker rmi pacur/pacur-genkey
 docker rmi pacur/pacur-oraclelinux-7
 docker rmi pacur/pacur-ubuntu-precise
 docker rmi pacur/pacur-ubuntu-trusty
 docker rmi pacur/pacur-ubuntu-vivid
 docker rmi pacur/pacur-ubuntu-wily
 docker rmi pacur/pacur-ubuntu-xenial
 docker rmi pacur/pacur-ubuntu-yakkety
 docker rmi pacur/pacur-ubuntu-zesty
 docker rmi pacur/pacur-ubuntu-artful
 docker rmi pacur/pacur-ubuntu-bionic
 docker rmi pacur/pacur-ubuntu-cosmic
 docker rmi pacur/pacur-ubuntu-disco
 docker rmi pacur/pacur-ubuntu-eoan
 docker rmi base/archlinux
 docker rmi archlinux/base
 docker rmi amazonlinux:2016.09
 docker rmi amazonlinux:2017.03
 docker rmi amazonlinux:2017.09
 docker rmi amazonlinux:2017.12
 docker rmi amazonlinux:1
 docker rmi amazonlinux:2
 docker rmi centos:6
 docker rmi centos:7
 docker rmi debian:jessie
 docker rmi debian:stretch
 docker rmi debian:wheezy
 docker rmi debian:buster
 docker rmi fedora:21
 docker rmi fedora:22
 docker rmi fedora:23
 docker rmi fedora:24
 docker rmi fedora:25
 docker rmi fedora:26
 docker rmi fedora:27
 docker rmi fedora:28
 docker rmi fedora:29
 docker rmi fedora:30
 docker rmi oraclelinux:7
 docker rmi ubuntu:precise
 docker rmi ubuntu:trusty
 docker rmi ubuntu:vivid
 docker rmi ubuntu:wily
 docker rmi ubuntu:xenial
 docker rmi ubuntu:yakkety
 docker rmi ubuntu:zesty
 docker rmi ubuntu:artful
 docker rmi ubuntu:bionic
 docker rmi ubuntu:cosmic
 docker rmi ubuntu:disco
 docker rmi ubuntu:eoan
 docker rmi $(sudo docker images -q -f dangling=true)