FROM archlinux/base
MAINTAINER pacur

RUN pacman -Syu --noconfirm \
&& pacman -S --noconfirm base-devel go git bzr mercurial wget rsync tar zip sudo \
&& ln -s -f /usr/bin/pinentry-curses /usr/bin/pinentry

ENV GOPATH /go
ENV PATH $PATH:/go/bin

RUN go get github.com/pacur/pacur \
&& sed -i 's|bsdtar -xf "$dbfile" -C "$tmpdir/$repo"|tar -xf "$dbfile" -C "$tmpdir/$repo"|g' /usr/bin/repo-add

ENTRYPOINT ["pacur"]
CMD ["build", "archlinux"]
